---
title: "Class 06: Why, when and how of writing my own R functons"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 1: Improving analysis code by writing functions

```{r}
# Improve this analysis code
df <- data.frame(a=1:10, b=seq(200,400,length=10),c=11:20,d=NA)
df$a <- (df$a - min(df$a)) / (max(df$a) - min(df$a))
df$b <- (df$b - min(df$a)) / (max(df$b) - min(df$b))
df$c <- (df$c - min(df$c)) / (max(df$c) - min(df$c))
df$d <- (df$d - min(df$d)) / (max(df$a) - min(df$d)) 
```

# Simplified the code first
x <- (x-min(x))/(max(x)-min(x))
# Reduced calculation duplication
xmin <- min(x)
x <- (x-xmin)/(max(x)-xmin)
rng <- range(x)
x <- (x-rng[1])/(rng[2]-rng[1])

# Turned the reduced code into a function
```{r}
rescale <- function(x) {
  rng <- range(x)
  (x-rng[1]) / (rng[2]-rng[1])
}

rescale(1:10)
```

## Improve the code for the analysis of protein drug interactions
```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

```{r}
plot_protein <- function (s) {
  s <- read.pdb(s) #s=name of the protein from data base
  s.chainA <- trim.pdb(s, chain = "A",elety="CA") #input = s
  s.b <- s.chainA$atom$b #input=s.chainA=trimmed s, assigning beta chain of residue from trimmed as s.b
  
  plotb3(s.b, sse=s.chainA, type="l", ylab="Bfactor") # inputs = s.b. & s.chianA, output = plot of residues
}
```

```{r}
plot_protein
```

```{r}
plot_protein("4AKE")
```

```{r}
plot_protein("1AKE")
```

```{r}
plot_protein("1E4Y")
```



